### ISSUE TITLE
Server returning 401 despite having access

### ISSUE THREAD

**Issue by AS94-Arc** [google/sa360-webquery-bigquery#17]
- I have 
   - agency admin access to SA360
   - owner access to the project

This is the account I authenticated Cloud SDK with on VM build from cloud shell

- The service account is designated to the VM and has 
   - advertiser access to SA360
   - editor access to bq & gcs

Is there a step missing on configuring ssh key for service account?

```
SEVERE: [Report 352726] Error Processing
java.io.IOException: Server returned HTTP response code: 401 for URL: https://searchads.google.com/ds/reports/download?ay=2...&av=2...&rid=3...&of=webqueryphtml&authuser=0
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
        at dswebquerytobigquery.WebQuery$WebQueryReader.getStream(WebQuery.java:97)
        at dswebquerytobigquery.WebQuery$WebQueryReader.writeAsCsv(WebQuery.java:104)
        at dswebquerytobigquery.TransferRunner.run(TransferRunner.java:64)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)```

**Comment by anantdamle** [comment]
@AS94-Arc thanks for flagging the issue. This is fixed in PR#18
You will need to update your VM  instance for SA360 scope using following command:

```shell script
gcloud compute instances set-service-account <INSTANCE-NAME> \
--zone <ZONE> \
--service-account <SERVICE-ACCOUNT-EMAIL> \
--scopes=https://www.googleapis.com/auth/cloud-platform,https://www.googleapis.com/auth/doubleclicksearch
```
